### ISSUE TITLE
Copying data folder when use Dockerfile

### ISSUE THREAD

**Issue by wallrony** [strongdm/accessbot#157]
**Describe the bug**
When I run the command `docker build .` the `data` folder is copied to the docker container. It's wrong because the data folder can have cache data related to configuration and other aspects of the bot, besides it throws the following error when the data folder has some `.db` files (I guess that's failing when starting to read the actual data that was written locally):

```bash
rony in accessbot on  main [✘!+?] took 2s 
❯ docker run -e SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN -e SDM_ADMINS=$SDM_ADMINS accessbot
2021-10-29 12:31:21,782 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
2021-10-29 12:31:21,788 INFO     errbot.bootstrap          Found Backend plugin: BotFramework
Traceback (most recent call last):
  File "/opt/conda/bin/errbot", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/errbot/cli.py", line 395, in main
    bootstrap(backend, root_logger, config, restore)
  File "/opt/conda/lib/python3.9/site-packages/errbot/bootstrap.py", line 257, in bootstrap
    bot = setup_bot(bot_class, logger, config, restore)
  File "/opt/conda/lib/python3.9/site-packages/errbot/bootstrap.py", line 172, in setup_bot
    repo_manager = BotRepoManager(storage_plugin, botplugins_dir, plugin_indexes)
  File "/opt/conda/lib/python3.9/site-packages/errbot/repo_manager.py", line 151, in __init__
    self.open_storage(storage_plugin, "repomgr")
  File "/opt/conda/lib/python3.9/site-packages/errbot/storage/__init__.py", line 34, in open_storage
    self._store = storage_plugin.open(namespace)
  File "/opt/conda/lib/python3.9/site-packages/errbot/storage/shelf.py", line 64, in open
    return ShelfStorage(new_spot)
  File "/opt/conda/lib/python3.9/site-packages/errbot/storage/shelf.py", line 15, in __init__
    self.shelf = shelve.DbfilenameShelf(path, protocol=2)
  File "/opt/conda/lib/python3.9/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/opt/conda/lib/python3.9/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available
```

**To Reproduce**
1. Set up a local python venv and install requirements (can be the common or dev requirements file);
2. Set up a `set-env.sh` file or set on your OS `SLACK_BOT_TOKEN` and `SDM_ADMINS` variables with their respective values;
3. Run `errbot` locally - and after it ran, cancel the execution;
4. Run `docker build -t accessbot .` to build accessbot image with the local Dockerfile;
5. Run `docker run -e SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN -e SDM_ADMINS=$SDM_ADMINS accessbot` and see the error.

**Expected behavior**
Is expected to don't copy the whole data folder, but just to create a data folder in the Docker container. So, instead of [line#18](https://github.com/strongdm/accessbot/blob/main/Dockerfile#L18) of the Dockerfile, add a make directory command to create the `data` folder.

**Desktop (please complete the following information):**
 - OS: Zorin OS 16;

**Comment by wallrony** [comment]
This issue was solved by [this commit](https://github.com/strongdm/accessbot/commit/7473868d134be05a20c90d3112b7ebb2affc51e2).
