### ISSUE TITLE
AccessBot hits rate limit processing "show_roles" with large number of users

### ISSUE THREAD

**Issue by mdube667** [strongdm/accessbot#166]
**Describe the bug**
Org with a large number of users hits "rate limited" when running show_roles which prevents it from finding the desired user

**To Reproduce**
I wasn't able to reproduce but it looks like it needs a large number of roles/users(they're pre-MR) for it to hit the limit. 

**Expected behavior**
Shouldn't hit the limit, maybe throttle itself in order to be able to find the requested user

**Screenshots**
Backtrace of Accessbot:

```
2021-11-23 15:49:12,684 INFO     errbot.core               Processing command "show_roles" with parameters "show available roles" from @timothy.smith

2021-11-23 15:49:13,658 ERROR    errbot.plugins.AccessBot  I got an error when trying to get the user profile, you might want to check your account limits.

The request to the Slack API failed. (url: https://www.slack.com/api/users.profile.get)

The server responded with: {'ok': False, 'error': 'ratelimited'}.

2021-11-23 15:49:13,831 ERROR    errbot.core               An error happened while processing a message ("show available roles"): Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/errbot/core.py", line 546, in _execute_and_send

    for reply in replies:

  File "/errbot/plugins/sdm/accessbot.py", line 86, in show_roles

    yield from self.get_show_roles_helper().execute(message)

  File "/errbot/plugins/sdm/lib/base_show_helper.py", line 11, in execute

    resources += self.get_line(item, message)

  File "/errbot/plugins/sdm/lib/show_roles_helper.py", line 15, in get_line

    account = self.__get_account(message)

  File "/errbot/plugins/sdm/lib/show_roles_helper.py", line 28, in __get_account

    return self.__sdm_service.get_account_by_email(sender_email)

  File "/errbot/plugins/sdm/lib/sdm_service.py", line 36, in get_account_by_email

    raise Exception("Sorry, cannot find your account!")

Exception: Sorry, cannot find your account!

"

Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/errbot/core.py", line 546, in _execute_and_send

    for reply in replies:

  File "/errbot/plugins/sdm/accessbot.py", line 86, in show_roles

    yield from self.get_show_roles_helper().execute(message)

  File "/errbot/plugins/sdm/lib/base_show_helper.py", line 11, in execute

    resources += self.get_line(item, message)

  File "/errbot/plugins/sdm/lib/show_roles_helper.py", line 15, in get_line

    account = self.__get_account(message)

  File "/errbot/plugins/sdm/lib/show_roles_helper.py", line 28, in __get_account

    return self.__sdm_service.get_account_by_email(sender_email)

  File "/errbot/plugins/sdm/lib/sdm_service.py", line 36, in get_account_by_email

    raise Exception("Sorry, cannot find your account!")

Exception: Sorry, cannot find your account!
```

**Comment by mdube667** [comment]
Version of accessbot is 1.3
