### ISSUE TITLE
AccessBot Hitting Slack Bolt API Rate Limit

### ISSUE THREAD

**Issue by marysdm** [strongdm/accessbot#250]
**Describe the bug**
Customer just configured AccessBot. After resolving an issue with the Slack Email configuration, they hit the Slack Bolt API rate limit. They have ~86 users, so doesn't make sense.

**To Reproduce**
Just setting up an env to attempt repro.
Essentially, they just setup AccessBot and hit the rate limit after correcting a configuration error with the slack email settings, they didn't setup variables so email was set to string literal "None" initially. After correcting this in the config and restarting the container, they hit this limit.

**Expected behavior**
Ideally, not being rate limited.

**Screenshots**
Traceback from the log:
`2022-05-17 12:47:25.844 PDT
Traceback (most recent call last): File "/opt/conda/lib/python3.9/site-packages/errbot/core.py", line 546, in _execute_and_send for reply in replies: File "plugins/sdm/accessbot.py", line 112, in assign_role yield from self.get_role_grant_helper().request_access(message, role_name) File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 28, in request_access yield from self.__grant_access(message, sdm_resource, sdm_account, execution_id, request_id, flags) File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 73, in __grant_access yield from self.__request_manual_approval(message, sdm_object, sdm_account, execution_id, request_id, sender_nick, flags) File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 97, in __request_manual_approval self.__check_administration_availability() File "/errbot/plugins/sdm/lib/helper/base_grant_helper.py", line 167, in __check_administration_availability if self.__bot.config['ADMINS_CHANNEL'] and not self.__bot.channel_is_reachable(self.__bot.config['ADMINS_CHANNEL']): File "plugins/sdm/accessbot.py", line 308, in channel_is_reachable return self._platform.channel_is_reachable(channel) File "/errbot/plugins/sdm/lib/platform/slack_platform.py", line 52, in channel_is_reachable channel_list = self._bot._bot.channels() File "errbot-slack-bolt-backend/errbot_slack_bolt_backend/slackbolt.py", line 730, in channels conversations = self.__fetch_conversations(joined_only=joined_only, exclude_archived=exclude_archived, types=types) File "errbot-slack-bolt-backend/errbot_slack_bolt_backend/slackbolt.py", line 735, in __fetch_conversations conversations = self.__get_conversations(**kwargs) File "/opt/conda/lib/python3.9/site-packages/memoization/caching/plain_cache.py", line 42, in wrapper result = user_function(*args, **kwargs) File "errbot-slack-bolt-backend/errbot_slack_bolt_backend/slackbolt.py", line 687, in __get_conversations conversations = Utils.get_items(self.__get_conversations_page, kwargs=kwargs) File "errbot-slack-bolt-backend/errbot_slack_bolt_backend/slackbolt.py", line 125, in get_items raise Exception("Too many requests were made. Please, try again in 1 minute.") from e Exception: Too many requests were made. Please, try again in 1 minute.`

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Latest version of the AccessBot

**IMPORTANT**: Remember to select a label and project

**Comment by wallrony** [comment]
hey @marysdm!
We tried to reproduce this error but we couldn't. We are testing in a pretty big organization with more than 5 thousand users and around 400 channels, so it's not clear to us that just setting the env configuration is causing this Exception. Can you please check if the costumer is still having this problem and provide us more details? Please ask the costumer to run the command `plugin info AccessBot` into Slack and share the output.
Thanks!

**Comment by sam-ewen** [comment]
FYI @wrenhunter

**Comment by marysdm** [comment]
@ wallrony This is still an issue. I've requested the info, will share when the customer comes back.

**Comment by marysdm** [comment]
Customer shared output as screenshots, this should be in order. Let me know if you need anything else. :)

![Screen Shot 2022-05-23 at 9 55 32 AM](https://user-images.githubusercontent.com/89810391/169871082-1981738d-f510-4f7c-94a0-77057e64969d.png)
![Screen Shot 2022-05-23 at 9 55 55 AM](https://user-images.githubusercontent.com/89810391/169871097-f360cf8e-79bd-4f19-ae16-92f661b54f9a.png)
![Screen Shot 2022-05-23 at 9 56 06 AM](https://user-images.githubusercontent.com/89810391/169871115-9544de1f-acd5-4e85-803a-63ce72da1547.png)

**Comment by marysdm** [comment]
Ack

**Comment by marysdm** [comment]
Customer has been silent since my request for full stack trace.
