### ISSUE TITLE
Newer versions of accessbot (appears to be v2.0.44+) print an error on startup; `status` does not work

### ISSUE THREAD

**Issue by alconen** [strongdm/accessbot#271]
**Describe the bug**
Newer versions of accessbot (appears to be v2.0.44+) return an error on startup. Condensed output:

```python
Error: Backup failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: ChatRoom failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Flows failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: TextCmds failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: CommandNotFoundFilter failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: VersionChecker failed to activate: 'NoneType' object has no attribute 'is_activated'.
```

This doesn't appear to break permission granting, but at least `status` no longer works when this occurs. 

**To Reproduce**
1. Update accessbot to v2.0.44+
2. Observe that an error is printed on startup and `status` does not work properly.

**Expected behavior**
Accessbot does not print out an error on startup; `status` command works properly.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS Focal

**Additional context**

This was first raised by a customer, but I was able to reproduce by updating to latest on an internal test instance. 

<details>
<summary>Full logging on startup</summary>

```python
2022-07-18 17:45:25,659 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
2022-07-18 17:45:25,664 INFO     errbot.bootstrap          Found Backend plugin: SlackBolt
2022-07-18 17:45:25,938 INFO     errbot                    webhooks: Flag to bind /echo to echo
2022-07-18 17:45:26,430 INFO     errbot.core               Activate internal commands
2022-07-18 17:45:26,430 INFO     errbot.plugin_manager     Activate bot plugins...
2022-07-18 17:45:26,430 INFO     errbot.plugin_manager     Activate plugin: Webserver.
2022-07-18 17:45:26,431 INFO     errbot.plugins.Webserver  Webserver is not configured. Forbid activation
2022-07-18 17:45:26,431 INFO     errbot.core_plugins.wsview Checking Webserver for webhooks
2022-07-18 17:45:26,432 INFO     errbot.core_plugins.wsview Webhook routing echo
2022-07-18 17:45:26,433 INFO     errbot.plugin_manager     Activate plugin: Help.
2022-07-18 17:45:26,434 INFO     errbot.core_plugins.wsview Checking Help for webhooks
2022-07-18 17:45:26,434 ERROR    errbot.plugin_manager     Error loading Backup.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/errbot/plugin_manager.py", line 444, in activate_non_started_plugins
    if not plugin.is_activated:
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-18 17:45:26,435 ERROR    errbot.plugin_manager     Error loading ChatRoom.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/errbot/plugin_manager.py", line 444, in activate_non_started_plugins
    if not plugin.is_activated:
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-18 17:45:26,435 ERROR    errbot.plugin_manager     Error loading Flows.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/errbot/plugin_manager.py", line 444, in activate_non_started_plugins
    if not plugin.is_activated:
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-18 17:45:26,435 ERROR    errbot.plugin_manager     Error loading TextCmds.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/errbot/plugin_manager.py", line 444, in activate_non_started_plugins
    if not plugin.is_activated:
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-18 17:45:26,435 INFO     errbot.plugin_manager     Activate plugin: Plugins.
2022-07-18 17:45:26,436 INFO     errbot.core_plugins.wsview Checking Plugins for webhooks
2022-07-18 17:45:26,437 INFO     errbot.plugin_manager     Activate plugin: Utils.
2022-07-18 17:45:26,437 INFO     errbot.core_plugins.wsview Checking Utils for webhooks
2022-07-18 17:45:26,438 INFO     errbot.plugin_manager     Activate plugin: ACLs.
2022-07-18 17:45:26,439 INFO     errbot.core_plugins.wsview Checking ACLS for webhooks
2022-07-18 17:45:26,439 ERROR    errbot.plugin_manager     Error loading CommandNotFoundFilter.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/errbot/plugin_manager.py", line 444, in activate_non_started_plugins
    if not plugin.is_activated:
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-18 17:45:26,439 ERROR    errbot.plugin_manager     Error loading VersionChecker.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/errbot/plugin_manager.py", line 444, in activate_non_started_plugins
    if not plugin.is_activated:
AttributeError: 'NoneType' object has no attribute 'is_activated'
2022-07-18 17:45:26,440 INFO     errbot.plugin_manager     Activate plugin: Health.
2022-07-18 17:45:26,440 INFO     errbot.core_plugins.wsview Checking Health for webhooks
2022-07-18 17:45:26,441 INFO     errbot.plugin_manager     Activate plugin: AccessBot.
2022-07-18 17:45:26,441 INFO     errbot.plugins.Webserver  Webserver is not configured. Forbid activation
2022-07-18 17:45:26,441 INFO     errbot.core_plugins.wsview Checking Webserver for webhooks
2022-07-18 17:45:26,442 INFO     errbot.core_plugins.wsview Webhook routing echo
2022-07-18 17:45:27,597 INFO     errbot.core_plugins.wsview Checking AccessBot for webhooks
2022-07-18 17:45:28,277 WARNING  errbot.core               Error: Backup failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: ChatRoom failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Flows failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: TextCmds failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: CommandNotFoundFilter failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: VersionChecker failed to activate: 'NoneType' object has no attribute 'is_activated'.

2022-07-18 17:45:28,277 INFO     errbot.core               Error: Backup failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: ChatRoom failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: Flows failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: TextCmds failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: CommandNotFoundFilter failed to activate: 'NoneType' object has no attribute 'is_activated'.
Error: VersionChecker failed to activate: 'NoneType' object has no attribute 'is_activated'.

2022-07-18 17:45:28,277 INFO     errbot.core               Notifying connection to all the plugins...
2022-07-18 17:45:28,277 INFO     errbot.core               Plugin activation done.
2022-07-18 17:45:28,278 INFO     errbot.backends.slackbolt Connecting to Slack socket
2022-07-18 17:45:28,554 INFO     slack_bolt.App            A new session has been established (session id: 6c74dcd1-0c0c-4ae2-a884-d6ecd836bd25)
2022-07-18 17:45:28,554 INFO     slack_bolt.App            ⚡️ Bolt app is running!
2022-07-18 17:45:28,579 INFO     slack_bolt.App            Starting to receive messages from a new connection (session id: 6c74dcd1-0c0c-4ae2-a884-d6ecd836bd25)
```

</details>

<details>
<summary>Config opts</summary>

```
      - SDM_EMAIL_SLACK_FIELD=Accessbot-Email
      - SDM_HIDE_RESOURCE_TAG=hide-resource
      - SDM_CONCEAL_RESOURCE_TAG=conceal-resource
      - SDM_AUTO_APPROVE_TAG=auto-approve
      - SDM_HIDE_ROLE_TAG=hide-role
      - SDM_GRANT_TIMEOUT=180
```
</details>

`status` doesn't seem to work properly, unsure if related:

```python
2022-07-18 17:27:58,424 INFO     errbot.plugins.ACLs       Matching ACL {'allowusers': [ **REDACTED**, '@william.majoros'], 'allowrooms': [], 'allowprivate': True, 'allowmuc': False} against username @william.majoros for command Health:status.
2022-07-18 17:27:58,425 INFO     errbot.core               Command None blocked or deferred.
```
It appears that there is a similar issue at https://github.com/errbotio/errbot/issues/1591, although the recommendation there to delete the `CORE_PLUGINS` prevented the container from starting properly, so may be unrelated.

**Comment by alconen** [comment]
https://github.com/strongdm/accessbot/issues/269 beat me to it, closing.
